In [77]:
inv_A.shape

(15, 5)

In [116]:
from scipy.optimize import linprog


low_percentage = 0.85
high_percentage = 1.05

A = np.random.rand(5,15)
inv_A = np.linalg.pinv(A)

c = np.zeros((5,))

A_c = np.concatenate((-inv_A,inv_A))
b1 = -np.ones((15,))*low_percentage
b2 = np.ones((15,))*high_percentage
b = np.concatenate((b1,b2))

res = linprog(c, A_ub=A_c, b_ub=b, bounds=((None,None),(None,None),(None,None),(None,None),(None,None)),
              options={"disp": True})

while (res.status != 0):
    A = np.random.rand(5,15)
    inv_A = np.linalg.pinv(A)

    A_c = np.concatenate((-inv_A,inv_A))
    res = linprog(c, A_ub=A_c, b_ub=b, bounds=((None,None),(None,None),(None,None),(None,None),(None,None)),
              options={"disp": False})

Optimization failed. Unable to find a feasible starting point.


In [122]:
from scipy.optimize import linprog


low_percentage = 0.85
high_percentage = 1.05

A = np.random.rand(5,15)
inv_A = np.linalg.pinv(A)

c = np.zeros((5,))

A_c = np.concatenate((-inv_A,inv_A))
b1 = -np.array(default_config)*low_percentage
b2 = np.array(default_config)*high_percentage
b = np.concatenate((b1,b2))

res = linprog(c, A_ub=A_c, b_ub=b, bounds=((None,None),(None,None),(None,None),(None,None),(None,None)),
              options={"disp": True})

while (res.status != 0):
    A = np.random.rand(5,15)
    inv_A = np.linalg.pinv(A)

    A_c = np.concatenate((-inv_A,inv_A))
    res = linprog(c, A_ub=A_c, b_ub=b, bounds=((None,None),(None,None),(None,None),(None,None),(None,None)),
              options={"disp": False})

Optimization failed. Unable to find a feasible starting point.


KeyboardInterrupt: 

In [121]:
A_c.shape

(30, 5)

In [120]:
b.shape

(30,)

In [38]:
import ppl
x = ppl.Variable(0)
y = ppl.Variable(1)
z = ppl.Variable(2)
cs = ppl.Constraint_System()
cs.insert(A_c[0][0]*x >= b[0])
cs.insert(y >= 0)
cs.insert(z >= 0)
cs.insert(x + y + z == 1)
poly = ppl.C_Polyhedron(cs)
poly.minimized_generators()

Generator_System {ray(-1, 1, 0), ray(-1, 0, 1), point(1/1, 0/1, 0/1)}

In [39]:
cs

Constraint_System {x1>=0, x2>=0, x0+x1+x2-1==0}

In [40]:
A_c.shape

(30, 5)

In [47]:
A_c[i][4]

-0.36736914152172345

In [48]:
b[0]

-0.84999999999999998

In [42]:
x = [0]*5

x1 = ppl.Variable(0)
x2 = ppl.Variable(1)
x3 = ppl.Variable(2)
x4 = ppl.Variable(3)
x5 = ppl.Variable(4)

    
cs = ppl.Constraint_System()

for i in xrange(0,30):
    cs.insert(A_c[i][0]*x1 + A_c[i][1]*x2+ A_c[i][2]*x3+ A_c[i][3]*x4 + A_c[i][4]*x5<= b[i])
    print cs
poly = ppl.C_Polyhedron(cs)
poly.minimized_generators()

Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}
Constraint_System {}


Generator_System {line(0, 0, 0, 0, 1), line(1, 0, 0, 0, 0), line(0, 1, 0, 0, 0), line(0, 0, 1, 0, 0), line(0, 0, 0, 1, 0), point(0/1, 0/1, 0/1, 0/1, 0/1)}

In [37]:
cs

Constraint_System {}

In [2]:
import ppl
x = ppl.Variable(0)
y = ppl.Variable(1)
z = ppl.Variable(2)
cs = ppl.Constraint_System()
cs.insert(x >= 0)
cs.insert(y >= 0)
cs.insert(z >= 0)
cs.insert(x + y + z == 1)
poly = ppl.C_Polyhedron(cs)
poly.minimized_generators()

Generator_System {point(1/1, 0/1, 0/1), point(0/1, 1/1, 0/1), point(0/1, 0/1, 1/1)}

In [3]:
%matplotlib inline
import matplotlib.pyplot as plt

import numpy as np
import rospy
from prx_simulation.msg import ControllerParams, LinGaussParams, TfParams, CaffeParams, \
                               TfActionCommand, gps_trial_command_msg,\
                               SampleResult, gps_state_command_msg, superball_T6_new_config,\
                                ObserverParams
from gps.agent.ros.ros_utils import ServiceEmulator
import rosbag

import GPy
import GPyOpt

import time
import random
from datetime import datetime

import dill
import pickle

from tqdm import *
import scipy.io
import copy
from numpy.random import seed

In [2]:
import polytope as pc
import numpy as np

In [3]:
A = np.array([[1.0, 0.0],
              [0.0, 1.0],
              [-1.0, -0.0],
              [-0.0, -1.0]])

b = np.array([2.0, 1.0, 0.0, 0.0])

p = pc.Polytope(A_c, b)

In [100]:
A_c.shape

(30, 5)

In [101]:
b.shape

(30,)

In [103]:
from scipy.optimize import linprog


low_percentage = 0.85
high_percentage = 1.05

A = np.random.rand(15,5)
inv_A = np.linalg.pinv(A)

c = np.zeros((5,))

A_c = np.concatenate((-A,A))
b1 = -np.ones((15,))*low_percentage
b2 = np.ones((15,))*high_percentage
b = np.concatenate((b1,b2))

res = linprog(c, A_ub=A_c, b_ub=b, bounds=((None,None),(None,None),(None,None),(None,None),(None,None)),\
              options={"disp": True})

while (res.status != 0):
    A = np.random.rand(15,5)
    inv_A = np.linalg.pinv(A)

    A_c = np.concatenate((-A,A))
    res = linprog(c, A_ub=A_c, b_ub=b, bounds=((None,None),(None,None),(None,None),(None,None),(None,None)),\
              options={"disp": False})

Optimization failed. Unable to find a feasible starting point.


In [104]:
res

     fun: -0.0
 message: 'Optimization terminated successfully.'
     nit: 25
   slack: array([ 0.2    ,  0.2    ,  0.2    ,  0.2    ,  0.02334,  0.01994,
        0.09153,  0.17229,  0.03555,  0.11841,  0.10874,  0.09867,
        0.05113,  0.2    ,  0.02064,  0.     ,  0.     ,  0.     ,
        0.     ,  0.17666,  0.     ,  0.     ,  0.02771,  0.     ,
        0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.17936])
  status: 0
 success: True
       x: array([ 0.38584,  0.64404,  0.28309,  0.32589,  0.35687])

In [137]:
low_percentage = 0.85
high_percentage = 1.05

A = np.random.rand(5,15)
inv_A = np.linalg.pinv(A)

c = np.zeros((5,))

A_c = np.concatenate((-inv_A,inv_A))
b1 = -np.ones((15,))*low_percentage
b2 = np.ones((15,))*high_percentage
b = np.concatenate((b1,b2))

res = linprog(c, A_ub=A_c, b_ub=b, bounds=((None,None),(None,None),(None,None),(None,None),(None,None)),
              options={"disp": True})

while (res.status != 0):
    A = np.random.rand(5,15)
    inv_A = np.linalg.pinv(A)

    A_c = np.concatenate((-inv_A,inv_A))
    res = linprog(c, A_ub=A_c, b_ub=b, bounds=((None,None),(None,None),(None,None),(None,None),(None,None)),
              options={"disp": False})

Optimization failed. Unable to find a feasible starting point.


In [138]:
res

     fun: -0.0
 message: 'Optimization terminated successfully.'
     nit: 20
   slack: array([ 0.19127,  0.10928,  0.01644,  0.2    ,  0.03953,  0.2    ,
        0.15594,  0.13755,  0.2    ,  0.02341,  0.17896,  0.2    ,
        0.2    ,  0.13046,  0.10847,  0.     ,  0.09072,  0.18356,
        0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ,
        0.     ,  0.     ,  0.     ,  0.     ,  0.     ,  0.     ])
  status: 0
 success: True
       x: array([ 6.05077,  6.02401,  6.06567,  8.30608,  7.25212])

In [269]:
p = pc.Polytope(A_c, b)

In [287]:
p.volume

7.6020942369654874e-06

In [231]:
p.chebR

0.014867305154413184

In [232]:
p.chebXc

array([ 6.12811,  6.07458,  6.11971,  8.32776,  7.29472])

In [243]:
p.bbox

(array([[ 6.04825],
        [ 6.01338],
        [ 6.06567],
        [ 8.25609],
        [ 7.21985]]), array([[ 6.62553],
        [ 6.50475],
        [ 6.3507 ],
        [ 8.64869],
        [ 7.81858]]))

In [242]:
polytope.grid_region(p)

(array([], shape=(5, 0), dtype=float64),
 [4.6182483085083277,
  3.9309718203973034,
  2.2802614658506144,
  3.1408178043479467,
  4.7898133469029389])

In [270]:
p.bounding_box

(array([[ 6.04825],
        [ 6.01338],
        [ 6.06567],
        [ 8.25609],
        [ 7.21985]]), array([[ 6.62553],
        [ 6.50475],
        [ 6.3507 ],
        [ 8.64869],
        [ 7.81858]]))

In [264]:
V_min = polytope.extreme(p)

In [273]:
p_reduced = polytope.reduce(p)

In [275]:
polytope.extreme(p_reduced).shape

(34, 5)

In [288]:
V_min

array([[ 6.10457,  6.06346,  6.07264,  8.35837,  7.34085],
       [ 6.22113,  6.11769,  6.08757,  8.37117,  7.44791],
       [ 6.20531,  6.08908,  6.08544,  8.30107,  7.37545],
       [ 6.08521,  6.06369,  6.13252,  8.34624,  7.35717],
       [ 6.21515,  6.13997,  6.11156,  8.4838 ,  7.48069],
       [ 6.0589 ,  6.02488,  6.13187,  8.25609,  7.26099],
       [ 6.10489,  6.09898,  6.20748,  8.30913,  7.31901],
       [ 6.05077,  6.02401,  6.06567,  8.30608,  7.25212],
       [ 6.0602 ,  6.01338,  6.06681,  8.25882,  7.21985],
       [ 6.09834,  6.06944,  6.10286,  8.30328,  7.251  ],
       [ 6.14987,  6.0598 ,  6.13114,  8.35378,  7.25054],
       [ 6.29493,  6.20637,  6.25233,  8.51543,  7.3358 ],
       [ 6.15636,  6.0892 ,  6.14525,  8.45679,  7.31237],
       [ 6.42668,  6.32146,  6.17854,  8.56997,  7.70742],
       [ 6.42677,  6.31705,  6.17589,  8.56271,  7.70459],
       [ 6.42465,  6.32107,  6.18305,  8.56868,  7.70811],
       [ 6.4264 ,  6.31988,  6.17875,  8.57577,  7.7087 

In [21]:
default_config = \
[         0.38618,    # density (kg / length^3) weight of both endcaps: 3.3kg (1.65 kg each)
         0.35,     # radius (length) radius of an endcap
         0.208,      # density_mp (kg / length^3) weight of connecting rod: 200g 
         0.175,      #radius_mp (length) radius of the connecting rod
         3152.36,  # stiffnessActive (kg / sec^2)
         200.0,    # damping (kg / sec)
         17.4,     # rod_length (length)
         4.5,      # rod_space (length)
         10.0,        # rod_length_mp (length)
         100.0,   # pretension -> set to 
         2000,   # maxTens
         2,    # targetVelocity
         0.09, # motor_radius # Spindle radius (length)
         2*4.24e-5, # motor_friction (kg*(length)^2/sec)
         4*2.749e-4, # motor_inertia (kg*(length)^2) # Inertia of motor, gearbox, and spindle all together
]

In [30]:
import numpy.matlib

In [277]:
total_sample = 10000
x_range = []
for i in xrange(0,total_sample):
    sample = np.random.random_sample((V_min.shape[0],))
    n_sample = sample/np.sum(sample)
    n_sample = np.array([n_sample,])
    n_sample = n_sample.T
    weighted_V = np.dot(V_min.T,n_sample)
    
    x_proj = np.multiply(np.squeeze(np.dot(inv_A,weighted_V)),np.array(default_config))
    x_range.append(x_proj)

In [278]:
x_range_array = np.asarray(x_range)

In [279]:
np.min(x_range_array,axis=0)

array([    0.3347 ,     0.33761,     0.17863,     0.15267,  3160.29588,
         170.90484,    17.29322,     4.26749,    10.38458,   104.30879,
        1812.74013,     1.70236,     0.08151,     0.00008,     0.00107])

In [280]:
np.max(x_range_array,axis=0)

array([    0.3421 ,     0.34436,     0.18128,     0.15773,  3196.49609,
         173.05939,    17.48356,     4.50019,    10.47915,   104.88798,
        1896.92881,     1.71719,     0.0875 ,     0.00008,     0.00111])

In [290]:
import itertools, copy

global A,inv_A

tlist = list(itertools.product(range(2), repeat=5))
num_possibilities = len(tlist)


x_range = np.zeros((num_possibilities, 15))

for i in xrange(0,num_possibilities):
    index = np.array(tlist[i])
    config = copy.deepcopy(p.bounding_box[0])
    for j in xrange(0,5):
        if index[j]==0:
            config[j] =p.bounding_box[0][j]
        else:
            config[j] =p.bounding_box[1][j]
#     print config
    x_range[i,:] = np.multiply(np.squeeze(np.dot(inv_A,config)),np.array(default_config))
# print "y_range shape: ", y_range.shape

In [291]:
p.bounding_box[0]

array([[ 6.04825],
       [ 6.01338],
       [ 6.06567],
       [ 8.25609],
       [ 7.21985]])

In [292]:
default_config

[0.38618,
 0.35,
 0.208,
 0.175,
 3152.36,
 200.0,
 17.4,
 4.5,
 10.0,
 100.0,
 2000,
 2,
 0.09,
 8.48e-05,
 0.0010996]

In [293]:
np.min(x_range,axis=0)

array([    0.26277,     0.28343,     0.14156,     0.11476,  2590.80888,
         133.16557,    12.06336,     3.26796,     6.47148,    71.96799,
        1401.01756,     1.30222,     0.06008,     0.00007,     0.00091])

In [294]:
np.max(x_range,axis=0)

array([    0.41801,     0.39345,     0.2152 ,     0.19856,  3727.46896,
         210.69522,    22.8165 ,     5.48212,    14.41965,   136.46306,
        2326.22456,     2.10852,     0.10927,     0.0001 ,     0.00127])

In [228]:
np.multiply(np.squeeze(np.dot(inv_A,p.bounding_box[0])),np.array(default_config))

array([    0.33385,     0.33115,     0.17715,     0.1491 ,  3152.16652,
         170.26168,    17.39732,     4.06033,    10.37384,   102.63106,
        1740.15323,     1.69439,     0.07628,     0.00008,     0.00103])

In [227]:
np.multiply(np.squeeze(np.dot(inv_A,p.bounding_box[1])),np.array(default_config))



array([    0.34693,     0.34573,     0.17961,     0.16422,  3166.11132,
         173.59911,    17.48254,     4.68975,    10.51728,   105.79998,
        1987.08889,     1.71635,     0.09307,     0.00009,     0.00115])

In [204]:
sample = np.random.random_sample((V_min.shape[0],))
n_sample = sample/np.sum(sample)
n_sample = np.array([n_sample,])
n_sample = n_sample.T
weighted_V = np.dot(V_min.T,n_sample)

x_proj = np.multiply(np.squeeze(np.dot(inv_A,weighted_V)),np.array(default_config))

In [205]:
x_proj

array([    0.33678,     0.34137,     0.18037,     0.15421,  3183.17299,
         171.79585,    17.36035,     4.3892 ,    10.42209,   104.64303,
        1846.33714,     1.70884,     0.08428,     0.00008,     0.00109])

In [203]:
np.dot(inv_A,weighted_V).shape

(15, 1)

In [197]:
weighted_V.shapeV_min

(5, 1)

In [198]:
inv_A.shape

(15, 5)

In [191]:
np.array([n_sample]).shape

(34,)

In [173]:
sample

array([ 0.25539,  0.25717,  0.23757,  0.31421,  0.63035,  0.32531,
        0.40195,  0.31021,  0.06875,  0.21498,  0.28922,  0.7878 ,
        0.20886,  0.29267,  0.80414,  0.21856,  0.26735,  0.58742,
        0.47817,  0.42861,  0.82003,  0.8752 ,  0.62843,  0.8922 ,
        0.76724,  0.42179,  0.63352,  0.02693,  0.73797,  0.01764,
        0.47926,  0.58851,  0.71003,  0.06262])

In [174]:
n_sample

array([ 0.01698,  0.0171 ,  0.0158 ,  0.02089,  0.04191,  0.02163,
        0.02673,  0.02063,  0.00457,  0.01429,  0.01923,  0.05238,
        0.01389,  0.01946,  0.05347,  0.01453,  0.01778,  0.03906,
        0.03179,  0.0285 ,  0.05452,  0.05819,  0.04178,  0.05932,
        0.05101,  0.02804,  0.04212,  0.00179,  0.04907,  0.00117,
        0.03187,  0.03913,  0.04721,  0.00416])

In [175]:
np.sum(n_sample)

0.99999999999999989

In [149]:
default_config_array = np.matlib.repmat(default_config, V_min.shape[0], 1)

In [144]:
default_config_array.shape

(34, 15)

In [145]:
np.dot(inv_A,V_min.T).shape

(15, 34)

In [146]:
A.shape

(5, 15)

In [147]:
inv_A.shape

(15, 5)

In [266]:
x_proj = np.multiply(np.dot(inv_A,V_min.T),default_config_array.T)

In [267]:
np.min(x_proj,axis=1)

array([    0.32825,     0.32921,     0.1768 ,     0.14875,  3110.1342 ,
         170.     ,    16.73399,     3.89942,     9.98388,   102.15229,
        1700.     ,     1.7    ,     0.0765 ,     0.00008,     0.00101])

In [268]:
np.max(x_proj,axis=1)

array([    0.362  ,     0.35438,     0.1869 ,     0.16549,  3253.25118,
         178.35276,    17.89852,     4.725  ,    10.5    ,   105.     ,
        2013.60562,     1.7862 ,     0.0941 ,     0.00009,     0.00115])

In [256]:
b1_plus.shape

[0.38618,
 0.35,
 0.208,
 0.175,
 3152.36,
 200.0,
 17.4,
 4.5,
 10.0,
 100.0,
 2000,
 2,
 0.09,
 8.48e-05,
 0.0010996]

In [261]:
np.asarray(default_config)*.85

array([    0.32825,     0.2975 ,     0.1768 ,     0.14875,  2679.506  ,
         170.     ,    14.79   ,     3.825  ,     8.5    ,    85.     ,
        1700.     ,     1.7    ,     0.0765 ,     0.00007,     0.00093])

In [262]:
V_min.shape

(34, 5)

In [160]:
np.multiply(b1_plus,np.array(default_config))

array([    0.32825,     0.2975 ,     0.1768 ,     0.14875,  2679.506  ,
         170.     ,    14.79   ,     3.825  ,     8.5    ,    85.     ,
        1700.     ,     1.7    ,     0.0765 ,     0.00007,     0.00093])

In [161]:
np.multiply(b2,np.array(default_config))

array([    0.40549,     0.3675 ,     0.2184 ,     0.18375,  3309.978  ,
         210.     ,    18.27   ,     4.725  ,    10.5    ,   105.     ,
        2100.     ,     2.1    ,     0.0945 ,     0.00009,     0.00115])